backend:
  name: gitea
  repo: kwang1235/blog.lunasonata
  api_root: https://gitea.kwang1235.synology.me/api/v1
  base_url: https://gitea.kwang1235.synology.me
  app_id: "c57c1e2d-b498-4e7d-a3fe-f67e17450f75"
  branch: main

media_folder: "public/images/uploads"
public_folder: "https://image.lunasonata.com"

collections:
  # 1. MDX 포스트 컬렉션
  - name: "blog_mdx"
    label: "블로그 글 (MDX)"
    folder: "src/content/blog"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "pubDate", widget: "datetime" }
      - { label: "설명", name: "description", widget: "string" }
      - { label: "커버 이미지", name: "heroImage", widget: "string", required: false }
      - { label: "본문", name: "body", widget: "markdown" }

  # 2. MD 포스트 컬렉션
  - name: "blog_md"
    label: "블로그 글 (MD)"
    folder: "src/content/blog"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "pubDate", widget: "datetime" }
      - { label: "설명", name: "description", widget: "string" }
      - { label: "커버 이미지", name: "heroImage", widget: "string", required: false }
      - { label: "본문", name: "body", widget: "markdown" }